// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo360MwxQvI3OSNSlzPCeuZwkjDN9IrhM',
    appId: '1:1056960355728:web:d7636be6d476b6b4546715',
    messagingSenderId: '1056960355728',
    projectId: 'fir-flutter-codelab-f0e95',
    authDomain: 'fir-flutter-codelab-f0e95.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f0e95.appspot.com',
    measurementId: 'G-ZS6WLN5Z32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfJ_4oRT0wHOiyKWUc4wN2VLeh6zBTSjM',
    appId: '1:1056960355728:android:09b34f328a459c8e546715',
    messagingSenderId: '1056960355728',
    projectId: 'fir-flutter-codelab-f0e95',
    storageBucket: 'fir-flutter-codelab-f0e95.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo360MwxQvI3OSNSlzPCeuZwkjDN9IrhM',
    appId: '1:1056960355728:web:ee774523d15dbeeb546715',
    messagingSenderId: '1056960355728',
    projectId: 'fir-flutter-codelab-f0e95',
    authDomain: 'fir-flutter-codelab-f0e95.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f0e95.appspot.com',
    measurementId: 'G-Z3QTCS6QW1',
  );
}
